#Minecraft server properties
#Sat May 23 15:23:11 GMT 2026
allow-flight=true
allow-nether=true
debug=false
difficulty=3
enable-command-block=true
enable-query=false
enable-rcon=false
force-gamemode=false
gamemode=0
generate-structures=true
generator-settings=
hardcore=false
level-name=world
level-seed=
level-type=DEFAULT
max-build-height=256
max-players=1000
max-world-size=29999984
motd=&8&lV.&7&lS.&f&lT.&6&lD
network-compression-threshold=256
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
resource-pack=
resource-pack-sha1=
server-ip=
server-name=V.S.T.D
server-port=25565
snooper-enabled=true
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
use-native-transport=true
view-distance=5
white-list=false
